### ISSUE TITLE
Consistent crash after editing intersection of Rainier/Boren and 12th

### ISSUE THREAD

**Issue by belt-drive** [dabreegster/abstreet#111]
Output file included. Working in the South Seattle map on sandbox mode. Game crashes either immediately when trying to simulate after loading saved edits or as soon as game is sped up to 3600x after loading. Last edit before crash behavior started was to modify signals at intersections of Rainier/Boren and 12th as well as Boren and Yesler.

[output.txt](https://github.com/dabreegster/abstreet/files/4860029/output.txt)

**Comment by dabreegster** [comment]
Thanks! The problem is `PermanentMapEdits::from_permanent` is generating turn groups before applying the `ChangeLaneType` commands. Working on fixing

**Comment by dabreegster** [comment]
Recording some thoughts because I'll inevitably revisit this later:
- Need to figure out a similar trick for lane reversals and modifications, because of the validation that happens there
- Should we lift turn groups out of ControlTrafficSignal? Don't want to store them for every intersection, so putting in Intersection as optional means we have to be careful about keeping things in sync. And this doesn't solve the problem -- when we do validate() inside import(), it'll still break. If we dodged this by storing an UnvalidatedControlTrafficSignal or something in EditCmd, then... that's equivalent to the hacky fix
- As we transform perma map edits to normal, apply as we go, so signals see the correct state. But then we have to clone map when we load the list of edits!
- store the invalid ControlTrafficSignal in map edits. then as we actually apply it, rewrite?

**Comment by dabreegster** [comment]
I'll send a link to the Mac build in about 30 mins, so you don't have to wait to Sunday for the fix. Or if you want to wait till sometime tomorrow, I think I can knock out #109 too.

Also this reminds me that updating the game will be slightly annoying. You'll have to copy over `data/player/edits` from where you're playing now into the new version, or you'll lose your edits. I'll think about how to make this less of a headache.

**Comment by belt-drive** [comment]
Awesome, thank you! Appreciate the comments diagnosing the issue, too. Interesting to see what's going on, and helps to make some sense of the commit.

I'm fine to wait until tomorrow for a fix to #109  as well. I see the .json files in the data/player/edits folder and can copy those over.

I also see some edit files in that folder that I saved but wasn't able to reload when I was playing the VIP challenge. I'll see if I can generate a repro and file a separate bug for that one.
