### ISSUE TITLE
Can't load edits involving lane reversals 

### ISSUE THREAD

**Issue by belt-drive** [dabreegster/abstreet#113]
Occurs in both scenario ("VIP commute") and sandbox mode. I previously made and saved edits. Now, I'm not able to load those edits using the drop down menu to load edits in the map editing screen.

More details:
-> Corresponding .json file for edits exists in the data/player/montlake folder for the edits that I want to load
-> If I try to save other edits with the same name as the "missing edits", I get a message saying that edits with that name already exist and asking if I want to overwrite. So, the file system is able to see the file even if the menu that loads edit files doesn't list it.
-> I am able to save and load other edits without a problem (e.g. doesn't seem to be a FILO issue or something like that)
-> Changing the name of the file and the "edits_name" field in the .json file to a new name doesn't solve the problem. The edits are still not listed in the menu of available edits files to load under the new name.

Tried including here the edits file that the game does not recognize, but Github is unjazzed about attaching .json files. Appended .txt to file name for upload purposes.
[Vee Eye Pee.json.txt](https://github.com/dabreegster/abstreet/files/4861799/Vee.Eye.Pee.json.txt)

**Comment by dabreegster** [comment]
The game filters out edits that are invalid. Either there's a bug compressing the list of commands when saving (so your edits were valid originally, but after saving they broke) or you hit something like the other bug, where the edits are valid, but when loading them, the representation becomes invalid again. I can figure it out from the .json, thanks!

**Comment by dabreegster** [comment]
Sorry for the delay. This is in the same spirit as the other bug with determining if traffic signal edits are valid during loading. When loading edits with a sequence of reversing lanes and changing lane types, it's important to check that the basemap hasn't changed entirely since the edits were made. For example, if somebody updates OSM and says a road only has 3 lanes, not 5, but somebody had edits referring to one of the extra lanes. The bug is happening even when the basemap isn't updated, because to validate command 5 in an edit list, you need to apply commands 1-4. That's a bit expensive to do for every single command for all edits when opening the load dialog.

Some ideas:
- List all files in the loader, then when you select one, actually try to apply it. If it fails, display an error message and go back to listing files. Doesn't quite work for determining if built-in proposals apply to a particular map.
- Can maybe filter out invalid commands automatically from edits and preserve the rest? Would need to make a copy and not erase original edits.

**Comment by dabreegster** [comment]
Sorry it took so long to sort this out. I'm going to tentatively declare victory. I've changed the saved edits to store a blanket override of all changes to one road, instead of individual commands to toggle one lane at a time. This deals with the out-of-order problem. I've also finished the piece that automatically upgrades edits in the "old" format to the new one; it should be invisible to you when it works.

Some of your old edits won't import, though -- the ones here and in #234 included. Fixing those up might be very hard and possibly not worth it. Going forward, I think you should be able to mix any edits however you like, save, load, etc, but unless you have old edits that won't import now and are important to preserve, I'm going to close this out, along with #234.
