### ISSUE TITLE
thread 'main' panicked at 'exact_slice(0m, 0.0033m) yielded empty slice', geom/src/polyline.rs:272:32

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#143]
`raw_map to InitialMap...
find each intersection polygon: 10,117/13,067... 2.4022sthread 'main' panicked at 'exact_slice(0m, 0.0033m) yielded empty slice', geom/src/polyline.rs:272:32`

This time I tried to import much larger area - full Kraków `'49.98066,19.7922,50.1157,20.07962'`

**Comment by dabreegster** [comment]
Looking into it. For my own notes, the bounds have to swap lat/lon for osmconvert: `osmconvert malopolskie-latest.osm.pbf -b=19.7922,49.98066,20.07962,50.1157 -o=krakow.osm`

**Comment by dabreegster** [comment]
![Screenshot from 2020-07-06 14-29-18](https://user-images.githubusercontent.com/1664407/86648098-6f815280-bf95-11ea-935f-e05d5b486e43.png)
The whole region imported. If you simulate, about 5 minutes in, there's a crash because the first few stops along bus route 103 have their order inverted, or (more likely) they're getting snapped to the wrong side of the road.

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/relation/10953889#map=18/50.06411/20.01920 have some `highway=bus_stop` incorrectly placed on the road. I will fix this and see whatever crash persists.

**Comment by matkoniecz** [comment]
Thanks again for a quick fix!

**Comment by matkoniecz** [comment]
I fixed OSM data, and I am now regenerating the map. I will open issue for crashes/issues that I will encounter, if any.
