### ISSUE TITLE
Is there a shell script that downloads data?

### ISSUE THREAD

**Issue by yurivict** [dabreegster/abstreet#159]
The ```getting-started``` document says:
> Grab the minimal amount of data to get started: cargo run --bin updater.

This seems to require to build an executable first.

My goal is to create a package. The package builder can't download anything during build. All files have to be downloaded upfront.

Is there a shell script that can download  the same files required for
```
runtime: seattle,huge_seattle,austin
input: seattle,huge_seattle,austin
```
?

Such script can be run by packagers to cleanly download the required data before the build.

**Comment by dabreegster** [comment]
The updater originally was a bash script, but since Windows doesn't have curl and other tools, it was hard to keep it cross platform. A Rust tool without external dependencies has been nice.

Can you build the updater during the download phase? Depending on wget, curl, unzip, other standard tools is OK during that phase, but not building a new tool? If so, we could have a bash script just for this. It would download all the relevant .zip files from `data/MANIFEST.txt` and put them in the right place.

**Comment by yurivict** [comment]
The updater fails for me:
```
$ cargo run --bin updater .
   Compiling serde_derive v1.0.110
   Compiling tokio v0.2.21
   Compiling futures-util v0.3.5
   Compiling rustls v0.17.0
   Compiling tokio-util v0.3.1
   Compiling tokio-rustls v0.13.1
   Compiling h2 v0.2.5
   Compiling hyper v0.13.6
   Compiling hyper-rustls v0.20.0
   Compiling serde v1.0.110
   Compiling serde_urlencoded v0.6.1
   Compiling reqwest v0.10.6
   Compiling updater v0.1.0 (/usr/ports/misc/abstreet/work/abstreet-0.2.2-18-g9f72b3dd/updater)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 57s
     Running `target/debug/updater .`
Unknown argument .
```

**Comment by dabreegster** [comment]
Don't pass a `.` at the end. That's in the instructions to end the sentence, but it looks like it's part of the command. >_<  Removing it

**Comment by yurivict** [comment]
Ok, it downloads files. I can live with running a special cargo-based target to download data when the port is updated.

Thank you!
