### ISSUE TITLE
use turn:lanes tag

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#166]
For, well turn and also for lane count

Also `turn:lanes:forward` and `turn:lanes:backward` if not used already

https://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane

https://www.openstreetmap.org/way/148469685#map=19/50.07356/20.01840&layers=N
![screen](https://user-images.githubusercontent.com/899988/86922709-514e5a80-c12d-11ea-9c8a-4f45c983f720.png)

**Comment by dabreegster** [comment]
Using them today, but there are definitely problems. https://github.com/dabreegster/abstreet/blob/187c8ad4c56cc119c52493210af8e340a167402d/map_model/src/objects/lane.rs#L216

I'll look into what happened here specifically

**Comment by dabreegster** [comment]
![screencast](https://user-images.githubusercontent.com/1664407/86959142-29053280-c112-11ea-95e7-6b27deda15a9.gif)

The bug was hardcoding certain behavior for roundabouts. Also, if you're interested, this `get_lane_types` function may be of general interest. Just based on OSM tags, it tries to figure out the number and type of lanes in each direction. I'm sure you could spot loads of incorrect assumptions it makes. One major gap it has today is only allowing one direction change -- aka, you can't have a two-way separated cycleway adjacent to a two-way driving road.
