### ISSUE TITLE
Drivers should stay in the right lane while entering highways

### ISSUE THREAD

**Issue by belt-drive** [dabreegster/abstreet#217]
Having backup at the on-ramp to the 1st Ave S bridge. Some of the backup is happening because people getting on to the highway are usually trying to immediately get into the left lane of the highway. This requires the intersection to be clear, which makes merging much slower. Would increase traffic flow if drivers entering from the on ramp stayed in the rightmost lane for some distance before trying to change lanes.
<img width="1280" alt="Screen Shot 2020-07-21 at 7 11 39 PM" src="https://user-images.githubusercontent.com/67647924/88126471-6fcd4080-cb86-11ea-9d90-f63788945765.png">

**Comment by dabreegster** [comment]
I just did some work simplifying the turns between different lanes. I'll take another stab tomorrow at making vehicles pick lanes more realistically. They're picking the lane closest to the center line simply because the score function for each lane doesn't break ties yet.

**Comment by dabreegster** [comment]
Getting much closer. This particular problem is now gone. Choice of lane is now more clear: https://github.com/dabreegster/abstreet/blob/dd3f3d14ab989ef7d699ae65cea4e4a9c1371e12/sim/src/router.rs#L400. I'll post a link to the new Mac build when it's completed.

Still more work left. At i5519 in this map, the rightmost lane only turns right, so the other two lanes have their offsets messed up, the penalties are wrong, and very silly behavior is happening.

**Comment by dabreegster** [comment]
With the next change that's almost done uploading, I'm declaring victory on this bug. I think the lane choice behavior is now pretty sane in most cases. By 7am on this map, the remaining problems don't seem to be caused by lane-changing. If you spot new situations where it looks wrong or is causing problems, please let me know!

With that being said, getting the south seattle map past 7am is still tough. Some of the problems are still on my end (#114), but I could use non-programming help:

- improving the lane tagging in OpenStreetMap, especially along Michigan St and E Marginal / Diagonal Ave. I'm picking on these two because I see jams forming here, and zooming in, some of the intersection geometry is funny, because the lane count isn't right. I've made spot fixes in the area from aerial and Bing streetside, but it's always easier to edit when you have prior knowledge of the area. I haven't biked this far south yet.
- experimenting with traffic signal timing. The triangle of doom at boren, yesler, and 12th and nearby at jackson and boren are hard to get right. I've fiddled manually to make one of the common sequences work out well, but then it breaks E/W-bound on Jackson a little later. At some point, I can go survey these in person, but it's possible to manually reason through timings for these that would work well. The only slightly weird feature to know about is `edit signal offset`, to make the timing relative to others. If you have ideas to make this easier to edit, let me know.

**Comment by dabreegster** [comment]
Mac build with these fixes: https://github.com/dabreegster/abstreet/suites/957706772/artifacts/12013130
