### ISSUE TITLE
bus routes - match bus stops to ways included in bus route

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#219]
`highway=bus_stop` should be matched to nearest road in bus route relation (if bus relation has nearby roads included)

https://www.openstreetmap.org/relation/9534983#map=18/50.04658/19.92480 

![screen03](https://user-images.githubusercontent.com/899988/88170183-8f637800-cc1d-11ea-8c68-7921c73f5363.png)

that AB Street represents as follows:

![screen01](https://user-images.githubusercontent.com/899988/88170072-5925f880-cc1d-11ea-81d8-e025088c12c2.png)

**Comment by dabreegster** [comment]
A/B Street isn't matching to the bus-only service road, because there are no sidewalks there:
![Screenshot from 2020-07-28 12-49-40](https://user-images.githubusercontent.com/1664407/88714007-05118d00-d0d1-11ea-8c6f-dc406ccd8b8e.png)
Unfortunately I think we're blocked on getting footways/trails in for this case.
![Screenshot from 2020-07-28 12-50-16](https://user-images.githubusercontent.com/1664407/88714038-0f338b80-d0d1-11ea-9efd-92cdc2344822.png)

**Comment by dabreegster** [comment]
Also for cases like this, properly representing the rail platform would be ideal. That's likely blocked on footways, for connectivity. And need to filter out / somehow handle platforms belowground.

**Comment by matkoniecz** [comment]
I just added missing footways, including `sidewalk=separate`

**Comment by dabreegster** [comment]
> I just added missing footways, including sidewalk=separate

Thanks! To clarify, I meant supporting footways in A/B Street generally, not ones missing here specifically.

**Comment by matkoniecz** [comment]
In this case footways were completely missing, so even `highway=footway` support would not help :)
