### ISSUE TITLE
What's the format for b - jump to specific time

### ISSUE THREAD

**Issue by xoob** [dabreegster/abstreet#24]
What's the time format to be used with the `b` command? I'm trying to enter `14:00:00` but it is rewritten to `14;00;00` and the jump doesn't work.

Related question, what's the best way to complete the Traffic Lights tutorial quickly? It keeps reporting "No data yet, run the simulation for longer".

**Comment by dabreegster** [comment]
14:00:00 should work. There's a slider you can use in the meantime. I'll look into the ; rewriting. I think Mac users have had trouble writing : at all before, because of how I'm translating events from winit.

You can drag the speed slider or press **[** and **]**. The traffic light tutorial and most parts of the UI are undergoing major changes right now. The HN post kind of caught me off-guard. :)  Expect lots to be broken, am working on it.

**Comment by xoob** [comment]
No worries, thanks for the fun game. Do you want me to keep logging bugs or hang back?

**Comment by dabreegster** [comment]
You're finding stuff I've missed, so please file bugs! Just don't base your final impression of this project on the very broken state it's in right now. :)

**Comment by dabreegster** [comment]
The 24-hour format should be more clear now; the text-box is autofilled with the current time. If you're having trouble entering the : key, let me know what platform you're on? I'm directly looking for glutin::VirtualKeyCode::Colon and assuming it handles the shift switch between : and ;
