### ISSUE TITLE
exit code: 0xc0000135, STATUS_DLL_NOT_FOUND

### ISSUE THREAD

**Issue by Blazar221** [dabreegster/abstreet#254]
I tried to run import.sh to add a new map, but it failed and reported the following information:
process didn't exit successfully: `target\release\importer.exe --oneshot=belltower.osm` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
My system is windows and I clicked the importer.exe, but it showed that the application cannot find "gdal202.dll", but I've already downloaded gdal from http://download.gisinternals.com/sdk.html and set the GDAL_PATH environement variable, and I found gdal202.dll in the /bin path. Looking forward to your help.

**Comment by dabreegster** [comment]
You should be able to remove `--features scenarios` from `import.sh` if you're building from source. That takes away the GDAL dependency. I have no idea why https://crates.io/crates/gdal-sys isn't finding the dll on your path, though

**Comment by Blazar221** [comment]
It works! Thanks a lot. Besides, you may want to know that the error report also showed "C:/Users/DELL/.cargo/bin/cargo.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory" at the end.

**Comment by dabreegster** [comment]
I'll close this bug, since the workaround is mentioned in `docs/dev.md` (but not in `new_city.md` -- would that have helped?)

You could open an issue in https://github.com/georust/gdal to see why it didn't find the dll; I have no knowledge of how that crate works, or how Windows dll paths work generally. But it's not important for A/B Street unless you were trying to run the importer for Seattle-specific traffic scenarios.
