### ISSUE TITLE
Crash: assertion failed: `(left == right)` at sim/src/mechanics/driving.rs:635:9

### ISSUE THREAD

**Issue by andrewguertin** [dabreegster/abstreet#28]
I'm getting a frequent crash at [sim/src/mechanics/driving.rs#L635](https://github.com/dabreegster/abstreet/blob/9c879ab48834b7db2fa72a527d460fb544725274/sim/src/mechanics/driving.rs#L635). It occurs after a few (game-time) hours of simulating huge_seattle with weekday_typical_traffic_from_psrc, if another crash doesn't happen first.

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `CarID(151715, Car)`,
 right: `CarID(176112, Bike)`', sim/src/mechanics/driving.rs:635:9
```

Attached a few logs of the last minute of console output with backtrace.

[driving.rs-635-1.txt](https://github.com/dabreegster/abstreet/files/3963779/driving.rs-635-1.txt)
[driving.rs-635-2.txt](https://github.com/dabreegster/abstreet/files/3963780/driving.rs-635-2.txt)

**Comment by dabreegster** [comment]
This one is fun. It happens around https://www.openstreetmap.org/#map=19/47.64773/-122.35331. Between Nickerson and Etruria, there are two OSM nodes, and the way things get chopped up, both ways wind up with a very short road between two intersections. So when I'm watching this, it looks like a car starts doing a turn that a bike is still working on, then the car clips through the bike, winds up one the target lane, and this assertion trips, because both look like the laggy head of the source lane. Except in reality, there are two super short roads between the same intersections, and the two agents are spread between them. I'm trying out a manual fix in the map_editor.
