### ISSUE TITLE
Crash: thread 'main' panicked at 'Bad DistanceInterval ... sim/src/lib.rs:430:13

### ISSUE THREAD

**Issue by andrewguertin** [dabreegster/abstreet#29]
I'm getting a frequent crash at [sim/src/lib.rs#L430](https://github.com/dabreegster/abstreet/blob/9c879ab48834b7db2fa72a527d460fb544725274/sim/src/lib.rs#L430) It occurs after a few (game-time) hours of simulating huge_seattle with weekday_typical_traffic_from_psrc, if another crash doesn't happen first.

```
thread 'main' panicked at 'Bad DistanceInterval 53.974m .. 37.974m', sim/src/lib.rs:430:13
```

Attached a few logs of the last minute of console output with backtrace.

[lib.rs-430-1.txt](https://github.com/dabreegster/abstreet/files/3963782/lib.rs-430-1.txt)
[lib.rs-430-2.txt](https://github.com/dabreegster/abstreet/files/3963783/lib.rs-430-2.txt)

**Comment by dabreegster** [comment]
Not offhand sure what's wrong here. I haven't attempted running the full scenario on huge_seattle in a while, so I'll give that a try in the next few days and crunch through all of these issues. Thanks for the logs!

**Comment by dabreegster** [comment]
![silly_parking](https://user-images.githubusercontent.com/1664407/71219592-799e6680-227a-11ea-99cf-1e8a2efb22f1.gif)
So a pedestrian had to walk really far to get to their car. When they finish getting in, turns out the best parking spot is the one they just left -- because the car happens to be parked all the way by their destination. There was a bug in the code to handle finding a parking spot on the same lane. Fixed it, so now they very realistically get in the car, wiggle out of the parking spot, realize they're silly, then wiggle right back in.
