### ISSUE TITLE
`cargo run --bin updater` connection reset by peer

### ISSUE THREAD

**Issue by jacktang** [dabreegster/abstreet#410]
First of all, thanks for the interesting project! I played the project on the browser and try to install on my machine from source code. When I run the command `cargo run --bin updater` to download some data, the connection always be reset by peer.

Part of logs
```
[DEBUG] hyper::proto::h1::io: read 96 bytes
[DEBUG] hyper::proto::h1::io: read 48 bytes
[DEBUG] hyper::proto::h1::io: read 96 bytes
[DEBUG] hyper::proto::h1::io: read 48 bytes
[DEBUG] hyper::proto::h1::io: read 96 bytes
[DEBUG] hyper::proto::h1::io: read 288 bytes
[DEBUG] hyper::proto::h1::io: read 240 bytes
[DEBUG] hyper::proto::h1::io: read 48 bytes
[DEBUG] hyper::proto::h1::io: read 96 bytes
[DEBUG] hyper::proto::h1::io: read 48 bytes
[DEBUG] hyper::proto::h1::io: read 48 bytes
[DEBUG] hyper::proto::h1::io: read 144 bytes
[DEBUG] hyper::proto::h1::conn: incoming body decode error: Connection reset by peer (os error 54)
[DEBUG] hyper::proto::h1::conn: error shutting down IO: Socket is not connected (os error 57)
[DEBUG] hyper::client: client connection error: error shutting down connection: Socket is not connected (os error 57)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Body, source: hyper::Error(Body, Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }) }', updater/src/main.rs:245:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And two questions here:

1. where would the download data write ?
2. If the downloading was failed, it continued from very beginning or the last failure?

Thanks!

**Comment by dabreegster** [comment]
Thanks for taking interest in the project!

The download is from S3 us-east-2, which might've had [some partial outage recently](https://status.aws.amazon.com/). I tried the updater a few times just now and haven't had any connection problems. There might be some different timeout/retry options I could set through `reqwest`; I'll look into that. The debug output from `hyper` is also pretty spammy, I'll see about cleaning it up.

Another temporary option to run locally but without building from source is to use the binary releases for your platform: https://github.com/dabreegster/abstreet/releases

> where would the download data write ?

It goes to `data/system/`. In case you're interested, https://dabreegster.github.io/abstreet/dev/data.html describes how all of this works. It's a little bit complicated, due to supporting both native and web and supporting versioned releases.

> If the downloading was failed, it continued from very beginning or the last failure?

From the last failure. If a file is only partly downloaded, then the incomplete file is discarded; it'd start over for that file next run.

**Comment by jacktang** [comment]
@dabreegster thanks for the explanation. I pulled the latest code and it worked very well 👍
