### ISSUE TITLE
Break up Leeds

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/abstreet#444]
Problem: it's huuuge and slow to run in dev mode

![image](https://user-images.githubusercontent.com/1825120/103585237-9f74c880-4eda-11eb-91dd-17f49977c82f.png)

**Comment by Robinlovelace** [comment]
https://dabreegster.github.io/abstreet/howto/new_city.html#including-the-city-to-ab-street-more-permanently

**Comment by Robinlovelace** [comment]
Brainwave on intuitive, need and semi-automated way to split it into 4 pieces, use parliamentary constituency areas, and add the centre to each one:

![image](https://user-images.githubusercontent.com/1825120/103591713-cb974600-4ee8-11eb-8827-6860501c4de3.png)

**Comment by Robinlovelace** [comment]
Result: 

![image](https://user-images.githubusercontent.com/1825120/103595597-bb389880-4ef3-11eb-8022-38fd68359e3a.png)

All the 4 new geojsons are:

https://github.com/ITSLeeds/leedsboundaries/blob/main/leeds_central.geojson

https://github.com/ITSLeeds/leedsboundaries/blob/main/leeds_east_edited.geojson

https://github.com/ITSLeeds/leedsboundaries/blob/main/leeds_north_edited.geojson

https://github.com/ITSLeeds/leedsboundaries/blob/main/leeds_west_edited.geojson

Next step: convert them into .polys and push them to the codebase. Any reminders on how to do that welcome but will save for another day! Progress...

**Comment by dabreegster** [comment]
These look much more tractable! (pun intended, if census tracts are also UK terminology)
Next steps would be https://dabreegster.github.io/abstreet/howto/new_city.html#including-the-city-to-ab-street-more-permanently, but simplified because Leeds is already set up.

- Use `geojson_to_osmosis` to get .poly's
- Put them in `importer/config/leeds/` and delete the old `center.poly`
- Update `nice_map_name`
- Run the importer locally to see how they turn out

After you send the PR, I can run the importer as well, and upload the pre-built maps to S3. (Ideally we would have some kind of automation do that for an approved PR, but that's barely on the radar right now.)

**Comment by Robinlovelace** [comment]
:+1: looking good, will try locally in a bit, chat soon!
