### ISSUE TITLE
Import Detroit

### ISSUE THREAD

**Issue by MattBurb** [dabreegster/abstreet#452]
I tried following [this tutorial](https://dabreegster.github.io/abstreet/howto/new_city.html) but there is no way to write in the command prompt, in fact it doesn't say where exactly "./importer" should be run. I am trying to import the area surrounding downtown Detroit, it should be mapped well.

**Comment by dabreegster** [comment]
I'll think about how to improve the docs -- the commands have to be run in a terminal (or command prompt, I think is how Windows calls it). I can do the import for you. Could you draw a polygon boundary around the area you like using http://geojson.io/#map=11/42.2979/-83.2688?

And are you using the web version, building from scratch, or did you download one of the .zip files? I can send the Detroit map in different ways depending.

**Comment by MattBurb** [comment]
Here's the geojson file: [detroitgeojson.zip](https://github.com/dabreegster/abstreet/files/5810400/detroitgeojson.zip)

And I am using the Windows binary release.

**Comment by dabreegster** [comment]
Thanks!
1) Download https://www.dropbox.com/s/gu66k29zeq3qf80/detroit.bin?dl=0
2) Make a new folder under `data\system` called `oneshot`, then a folder in there called `maps`
3) Move `detroit.bin` into that folder, so you should wind up with `data\system\oneshot\maps\detroit.bin`
4) Run the game, open a new map, pick `oneshot` on the left side

Usually you could just use the "Download new cities" button from the game, but I changed the map format used since the release from this Sunday. I can include the map in the game normally starting with the next release this Sunday, though.

Detroit looks pretty well-mapped -- number of lanes looks reasonable, no crazy shaped junctions.

**Comment by MattBurb** [comment]
I managed to get it to work with the previous version.

Looks good, but I do have to question this..it happens at three different locations along this road.
![image](https://user-images.githubusercontent.com/77400079/104499972-ceaaca00-55ab-11eb-8621-8c0c43048d83.png)

**Comment by dabreegster** [comment]
Ah, good catch, and hopefully the sort of thing this tool can help you find! It's a bit convoluted, but you can directly jump to OSM from this tool by pressing **Ctrl+S** (dev mode will appear in the bottom right), clicking the road, going to the debug tab, and opening the OSM way (or just looking at the attributes there).

Alternatively, in the .zip folder, try out the `osm_viewer.exe` tool -- it has a slightly different UI that's hopefully easier for validating OSM.

https://www.openstreetmap.org/way/685412911
I've seen this kind of mistake happen very frequently when a bidirectional road is split into two one-ways. There shouldn't be lanes:backward on a one-way usually.

**Comment by dabreegster** [comment]
From my understanding of all the tags, I think that piece should be tagged `lanes=3` without `lanes:forward` and `lanes:backward` at all, since `oneway=yes`. And also `sidewalk=both` isn't accurate; `sidewalk=right` makes more sense.

Also check out https://wiki.openstreetmap.org/wiki/Tag:dual_carriageway%3Dyes. A/B Street might make use of this in the future to render the median.

**Comment by dabreegster** [comment]
Added to regular imports. I'll close out this bug, unless you have other questions/ideas. If you're looking into improving OSM quality in the area, street parking tags are the main missing thing I spot. They're useful for inferring road width. https://dabreegster.github.io/abstreet/side_projects/parking_mapper.html
