### ISSUE TITLE
Community Proposals: "Convert Lake WA Blvd to a SHS" won't load

### ISSUE THREAD

**Issue by moo** [dabreegster/abstreet#462]
Under "Community Proposals", selecting "Convert Lake Washington Blvd to a Stay Healthy Street" opens a loading screen, but then returns: 
"Can't load proposal 
Can't find OriginalRoad(...)" 

![Screen Shot 2021-01-18 at 10 17 34 PM](https://user-images.githubusercontent.com/34842/104995403-1a5dd900-59db-11eb-87e8-e7610595d176.png)

This happens on both Mac app 0.2.27 and in browser on Mac Chrome.

**Comment by dabreegster** [comment]
Good catch, thanks! The release process is missing a step to check that these built-in proposals still work. I'll fix this particular problem and add in that test.

**Comment by dabreegster** [comment]
So the test already exists and does the right thing: https://github.com/dabreegster/abstreet/blob/dfd1d2af934709da4268f2a890ea978f0516c14d/tests/src/main.rs#L138
But I've gotten sloppy when running it and wound up ignoring the results, partly because the reporting at the end of running this tool is overwhelming. I'm looking into that as part of #262.
